version: '3'
services:
  pmsapp-staging:
    build:
      args:
        user: pmsapp-api-user
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: pmsapp-api-staging
    container_name: pmsapp-staging
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: pmsapp-staging
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker-compose/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - pmsapp-api-network-staging

  webserver-staging:
    image: nginx:alpine
    container_name: pmsapp-api-server-staging
    restart: unless-stopped
    tty: true
    ports:
      - "5455:80"  # Staging uses a different port
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/conf.d/app-staging.conf:/etc/nginx/conf.d/
    networks:
      - pmsapp-api-network-staging

networks:
  pmsapp-api-network-staging:
    driver: bridge
